### ISSUE TITLE
GitHub issue with two Linear tickets IDs: `[ABC-2][ABC-1] GitHub issue`

### ISSUE THREAD

**Issue by woodwm** [calcom/synclinear.com#135] opened 2023-09-19 07:14 UTC
Hi,

A new issue is created in `Backlog` in Linear when I tag a issue `In Progress` as `Public`. In Github, this results in two linear issue IDs in front of the issue title. I am not sure why this is designed as such.

**Comment by tedspare** [comment] 2023-09-20 15:22
Hi @woodwm, thanks for bringing this up. Have seen something similar so I'm going to re-phrase the title of this issue. Will try to replicate it.

**Comment by xiaofei-du** [comment] 2023-09-20 18:43
I have encountered the same issue 🙏 
Quote here: https://github.com/calcom/synclinear.com/issues/134#issuecomment-1727653415

**Comment by tedspare** [comment] 2023-09-20 18:56
Thanks for linking to this, @xiaofei-du! I think there's a race condition, where the newly-created GH issue triggers a webhook before it's been added to the DB. Looking into it.

**Comment by woodwm** [comment] 2023-09-21 06:10
Hi,

In my case, two things happens. 

1. there are two Linear ID in the github issue.
2. There is a new Linear issue created in the `Backlog`

Image 1:

![image](https://github.com/calcom/synclinear.com/assets/13971199/6c0ec95f-b4d5-4b6c-9a8e-ae25869aa5c0)

Image 2:

![image](https://github.com/calcom/synclinear.com/assets/13971199/66a7372f-3a06-4894-8773-9f4420c54193)

**Comment by simkimsia** [comment] 2023-09-23 03:32
Subscribing to this because I have the same issue

**Comment by markphelps** [comment] 2023-10-26 14:37
this seems to be happening now for every issue we sync from Linear -> Github via the 'Public' label which makes it almost unusable

Here is the latest example: https://github.com/flipt-io/flipt/issues/2294

**Comment by aseba** [comment] 2023-10-31 15:32
Same issue for me on a fresh install if synclinear with configurations as default. Whenever I add the label "Public" it creates the issue in GH and immediately after creates a new one in Linear and appears in "triage" section.

**Comment by trietsch** [comment] 2023-11-15 08:40
Can confirm this is happening to our workspace / GitHub repo too. Quite difficult, as both Linear tickets are linked to the GitHub issue. Closing either Linear ticket results in closing the GitHub issue, so I have to keep both open.

**Comment by trietsch** [comment] 2023-11-15 08:52
@tedspare regarding reproducing the issue, I believe this might be caused by multiple team members having set up the same sync. As the sync to Linear wasn't working for other team members when I had configured it for one of our repositories, other team members also configured the same sync.

**Comment by kembala** [comment] 2023-11-27 11:17
Experiencing similar behavior. We have opened an issue on Github which resulted in the following traces.
Unsure about what is causing this, but wanted to share it might help to unpack.

<img width="869" alt="Screenshot 2023-11-27 at 12 14 59" src="https://github.com/calcom/synclinear.com/assets/2996824/b525c267-c038-48e8-8af0-5d77689baa69">
<img width="399" alt="Screenshot 2023-11-27 at 12 16 32" src="https://github.com/calcom/synclinear.com/assets/2996824/fc5f771b-02fe-4271-afa8-21f8f390aed0">
<img width="869" alt="Screenshot 2023-11-27 at 12 16 19" src="https://github.com/calcom/synclinear.com/assets/2996824/d13b1659-9480-47eb-9310-ba1b5bf452bf">
<img width="869" alt="Screenshot 2023-11-27 at 12 16 10" src="https://github.com/calcom/synclinear.com/assets/2996824/f1c49f5d-3467-4d40-99db-759846e9aa18">

**Comment by tedspare** [comment] 2023-11-27 16:13
Thanks for bumping.

This seems to happen when the issue creation triggers a GitHub webhook before it's been added to our DB.

A possible stopgap solution is to skip GH issues starting with `[ABC-123]`. Will implement this.

**Comment by tedspare** [comment] 2023-11-27 18:28
Should be prevented by 01c38f6eace05b6d0397b300f7d49e72ecf1c308

**Closed by tedspare** 2023-11-27 18:28 UTC
Labels: bug, linear
