### ISSUE TITLE
Sync fails to save with Linear Team ID upsert error

### ISSUE THREAD

**Issue by tborychowski** [calcom/synclinear.com#102] opened 2023-06-07 07:50 UTC
I tried using this app and it doesn't seem to work for me.
This is the body of the response from gh webhook settings:

```json
{"success":false,"message":"Could not find issue's corresponding sync."}
```

I did get an error when setting it up. This showed up after I clicked on "Deploy Github  Hook" button:
<img width="933" alt="2023-06-07 at 08 43 40@2x" src="https://github.com/calcom/synclinear.com/assets/392513/d832711a-bb0b-448f-8bdf-5c5a535daf8d">

**Comment by tedspare** [comment] 2023-07-03 21:38
Thanks @tborychowski. The problem probably does stem from that failed step during setup. Could you try syncing again? Does the same happen again? Thanks

**Comment by tedspare** [comment] 2023-07-05 18:49
Thanks for trying a few things @tborychowski. Looking into it now - what's the name of your Linear org? I wonder if it was never saved to the DB. An improvement to this flow has been pushed up - please feel free to try again.

As well, can you see the webhook under your Linear team > Settings > API > Webhooks?

**Comment by tedspare** [comment] 2023-07-05 18:53
Closing as duplicate of #61

**Closed by tedspare** 2023-07-05 18:53 UTC
Labels: bug

**Comment by tborychowski** [comment] 2023-07-06 12:33
Thanks @tedspare,
I tried again and the same error happens:
<img width="833" alt="2023-07-06 at 13 27 54@2x" src="https://github.com/calcom/synclinear.com/assets/392513/a9de4547-f43b-4e6e-827f-06bad04aabb1">

the sync doesn't work for me neither way.
My org name is 'perfectthings'.
